### ISSUE TITLE
After creditmemo order goes to processing

### ISSUE THREAD

**Issue by michael85a** [mollie/Magento#134] opened 2019-08-14 08:01 UTC
After credit memo is created in backend (based on invoice) we receive webhook and it runs Mollie_Mpm_Model_Client_Orders::processTransaction 
over here there is no handle of amountRefunded 
it is trying to handle amountCaptured and makes order processing again

**Comment by Frank-Magmodules** [comment] 2019-08-14 08:17
Hi @michael85a ,

Thank you for your message, as i'm not able to reproduce this, please share more exact information? Let me know which Magento and Mollie version you are using and please provide the exact steps on how we can reproduce this issue.

Frank

**Comment by michael85a** [comment] 2019-08-14 08:19
mollie 5.4
Magento ver. 1.9.3.2

**Comment by Frank-Magmodules** [comment] 2019-08-14 08:25
Hi @michael85a ,

Strange but can you please provide the exact steps? We do need information on how to reproduce this. Otherwise please share your login details so we can take look with you through our [contact form](https://www.magmodules.eu/contact-us.html) but we do need more information as ; 

- From which moment did this issue occur, after an update? Fresh installation?
- Does this issue occur on the OrderAPI or PaymentAPI?

etc.etc. the more information, the better.

Frank

**Comment by michael85a** [comment] 2019-08-14 08:29
process is following:
open order > invoices (left menu) > click invoice > credit meme (right above) > 'refund' (orange right button below)\

payment method iDeal
Method: **Order API**

after refund is created in mollie via event sales_order_creditmemo_save_after runs **Mollie_Mpm_Model_Observer::salesOrderCreditmemoSaveAfter**

we are receiving an webhook (checked in log file) 
webhook is processed by  action
**Mollie_Mpm_ApiController:: webhookAction()**

**$this->mollieModel->processTransaction($orderId, 'webhook');**

and in processTransaction the problem is

**Comment by Frank-Magmodules** [comment] 2019-08-14 08:53
Hi @michael85a , 

Strange, i can't reproduce this issue in our environment, the orderstatus just keeps "Closed" after a full credit. Please share your login details so we can take look with you through our [contact form](https://www.magmodules.eu/contact-us.html).

Frank

**Comment by michael85a** [comment] 2019-08-14 09:09
I asked client to confirm.

Before that i have following question:
When webhooks are sended, after which actions ? 
Can you check your log files if there are some webhook sended after credit memo was created in magento?

**Comment by Frank-Magmodules** [comment] 2019-08-14 09:14
Hi @michael85a , seems we've found something that could reflect on this. I will check this with our DEV team and let you know our founds asap.

Thank you for your patience here!

Frankk

**Comment by Frank-Magmodules** [comment] 2019-08-14 11:06
Hi @michael85a , thanks again for detailed issue report. 
The issue has been resolved in the [v5.5.0](https://github.com/mollie/Magento/releases/tag/v5.5.0) release. 
We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed** 2019-08-14 11:07 UTC
