### ISSUE TITLE
Amount paid not always set

### ISSUE THREAD

**Issue by dverkade** [mollie/Magento#189] opened 2020-10-07 08:34 UTC
I'm seeing a scenerio where the amount paid is not always set on an order. This will cause the order to not move to the next order state and it will never get to "complete". 

![image](https://user-images.githubusercontent.com/1058480/95307195-9f880c80-0888-11eb-9fd4-32a5d36be1b7.png)
![image](https://user-images.githubusercontent.com/1058480/95307257-b169af80-0888-11eb-9e09-c6bed2eceae6.png)

**Comment by Frank-Magmodules** [comment] 2020-10-08 08:40
Hi @dverkade , 

Thank you for opening and reporting this issue. Which version of Magento and Mollie are you using in this environment? 

Frank

**Comment by dverkade** [comment] 2020-10-08 08:46
Magento version:  1.9.4.5
Mollie version: 5.6.1

**Comment by Frank-Magmodules** [comment] 2020-10-08 10:02
Thanks for your reply @dverkade, it seems that i can't reproduce in our environment with the same versions. Is this something you always experience or do you have any specific steps to reproduce this? 

If possible, can you please share the /var/log/mollie.log file through our [contact form.](https://www.magmodules.nl/support-form.html) together with a screenshot from Mollie Webhook flow from the mollie Dashboard on this order so we can take a look with you on this and help you solve this issue?

Thanks again!

**Comment by dverkade** [comment] 2020-10-13 08:16
Thanks, and submitted the log file to you via the contact form. It only occurs on some orders, not every order. So that makes it a strange situation.

**Comment by Frank-Magmodules** [comment] 2020-12-28 15:20
Hi @dverkade,
We are happy to share that the fix that we've shared directly with you earlier, is just released into the new [5.6.2 ](https://github.com/mollie/Magento/releases/tag/v5.6.2)version. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed** 2020-12-28 15:23 UTC
