### ISSUE TITLE
Quickwin expose transaction id in inflo block when communicating with mollie helpdesk

### ISSUE THREAD

**Issue by seansan** [mollie/Magento#177] opened 2020-05-01 15:47 UTC
Quickwin expose transaction id in inflo block when communicating with mollie helpdesk

maybe it is 5 mins work to put a link under it directly to the backend ;)

template

            <?php if ($lasttransid = $this->getLastTransId()): ?>
                <tr>
                    <td class="label"><?= $this->__('Transaction Id'); ?></td>
                    <td class="value"><?= $lasttransid; ?></td>
                </tr>
            <?php endif; ?>

block

    /**
     * @return string
     */
    public function getLastTransId()
    {
        try {
            $lasttransid = $this->getInfo()->getLastTransId();
            return $lasttransid;
        } catch (\Exception $e) {
            $this->mollieHelper->addTolog('error', $e->getMessage());
        }
    }

**Comment by seansan** [comment] 2020-05-01 15:51
Only thing to create the quicklink would be to store the org code under settings ... maybe something to store anyhow (first thing they ask when calling customer helpdesk)

            <?php if ($lasttransid = $this->getLastTransId()): ?>
                <tr>
                    <td class="label"><?= $this->__('Transaction Id'); ?></td>
                    <td class="value"><a href="https://www.mollie.com/dashboard/org_<ORGCODEHERE>/payments/<?= $lasttransid; ?>" target="_blank"><?= $lasttransid; ?></a></td>
                </tr>
            <?php endif; ?>

**Comment by Marvin-Magmodules** [comment] 2020-05-05 13:10
Hi @seansan this issue is a duplicate of https://github.com/mollie/Magento/issues/175. Adding a link is a nice feature and we will add this to the backlog for the Magento 2 version. However, we will not implement this in the Magento 1 module as the focus has shifted to Magento 2 and this data is (transaction id) available under "Comments History" and also available under the tab "Transactions".

**Closed by Marvin-Magmodules** 2020-05-05 13:10 UTC
