### ISSUE TITLE
Issue with 5.5.1

### ISSUE THREAD

**Issue by patricksteenks** [mollie/Magento#145] opened 2019-09-25 09:14 UTC
I just downloaded and installed Mollie 5.5.1 module. However, the lib/Mollie directory is empty in Git. It appears to be ignored somehow?

I fixed it by downloading release 5.5.0 which does contain the lib/Mollie directory with files included.

**Comment by Frank-Magmodules** [comment] 2019-09-25 09:20
Hi @patricksteenks, did you download the [mollie-magento-5.5.1.zip](https://github.com/mollie/Magento/releases/download/v5.5.1/mollie-magento-5.5.1.zip) zip from the [releases](https://github.com/mollie/Magento/releases) page? 
As this is the drop-in package that included the lib folder.

**Comment by patricksteenks** [comment] 2019-09-25 09:41
No, I downloaded the Master page from the github main page. There must be the problem, thanks.

I have installed the latest version, but I do have a problem with this extension. The magento order status is not updated after a succesfull payment. Before we ran 5.0.4 and everything worked fine. But now it appears the webhook somehow is not called? How can I debug? I don't see anything strange in the mollie.log.

**Comment by Frank-Magmodules** [comment] 2019-09-25 09:53
Hi @patricksteenks , 
Yes, that doesn't contain the /lib folder so that was the issue.

About your second issue, are you sure your store is accessible for the Mollie Webhook and the store is not behind an IP and/or Htaccess block for example?

**Comment by patricksteenks** [comment] 2019-09-25 10:31
Yes, as I said, nothing changed except for the Mollie plugin update. Now dowgraded to 5.0.4 and the statuses are updated as expected. I'm not suren if something has changed in the new version regarding the webhook/updating of statuses?

**Comment by Frank-Magmodules** [comment] 2019-09-25 12:16
@patricksteenks , sorry, just checking as no major edits were made in the WebHook. 
You can check the WebHook result in the mollie dashboard in the right column on order level so can you check what the result was of this WebHook call? 

About the update, an extra check, sure you did, but i need to ask, cache was flushed and if Magento is running in compilation modus, you recompiled the code?

**Comment by patricksteenks** [comment] 2019-09-25 14:18
Yes, I did clear the cache and compilation is not turned on.

In Mollie I can see the webhook result and they are give "succes" back. See attached screenshot.

<img width="312" alt="Schermafbeelding 2019-09-25 om 16 17 01" src="https://user-images.githubusercontent.com/83209/65609434-0f926000-dfb0-11e9-8689-4756c03ec821.png">

**Comment by patricksteenks** [comment] 2019-09-25 14:20
But in Magento order status is still Pending. And I can also see that no invoice is generated for this order. Maybe the conflict is there?

**Comment by Frank-Magmodules** [comment] 2019-09-25 14:51
Hi @patricksteenks , strange, we can't reproduce this issue in our environment. 

Can you please [contact](https://www.magmodules.nl/contact-us.html) us directly with your server/temporary login details so we can help you debugging the issue? Preferably access to a staging / development environment so we can debug this for you.

**Comment by patricksteenks** [comment] 2019-09-25 14:54
OK, will do that, but will need some more time to set up the staging environment with the new version of the plugin. I will get back to you.

**Comment by Frank-Magmodules** [comment] 2019-09-25 15:05
Great @patricksteenks , whenever you are ready. Thanks!

**Comment by Marvin-Magmodules** [comment] 2019-10-11 13:46
Hi @patricksteenks, thanks again for detailed issue report and logins to the dev. When wrapping a $order->save() in a transaction, the update of the grid is postponed to a later action, however due to a log observer (or when disabling logging in the backend) the afterCommitCallback is not called. In both cases we call the `commit()` method of the order ourselves, so the afterCommitCallbacks are still called.

The workaround is inplemented in the [v5.5.2](https://github.com/mollie/Magento/releases/tag/v5.5.2) release. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Marvin-Magmodules** 2019-10-11 13:46 UTC

**Comment by milch-shake** [comment] 2019-10-15 14:09
i had the same issue - after updating to 5.5.2. the status might be correct - but the payment method is not shown in the overview
![15-10-_2019_16-07-22](https://user-images.githubusercontent.com/1479548/66839114-336d1400-ef66-11e9-89f4-ee2594c7e9d5.jpg)
