### ISSUE TITLE
Klarna Pay Later Payment Fee Tax Class incorrect Tax calculations

### ISSUE THREAD

**Issue by kasper-agg** [mollie/Magento#222] opened 2022-06-15 10:56 UTC
**Setup:**

OpenMage LTS 19.4.15
mollie/Magento 5.6.8

Setting:
Payment fee: 1.95
Tax class: Taxable Goods (21%)

Shopping cart display:
- Display Prices: Including and Excluding tax
- Display Subtotal: Including and Excluding tax 
- Display Shipping: Including
- Include Tax in grand total: Yes
- Display full tax summary: no
- Display zero tax subtotals: no

Orders, Invoice, Credit Memo Display Settings:
- Display Prices: Ex
- Display Subtotal: Ex
- Display Shipping: Ex
- Include Tax in grand total: Yes
- Display full tax summary: No
- Display zero tax subtotals: No

**Steps to reproduce:**
Add an item to cart.
Checkout, chose Klarna (Payment Fee becomes visible).
Proceed to test checkout and authorize payment.

Results split per page:

**Checkout summary:**
Item: € 4,16
Checkout totals shows: Payment Fee | € 1,95 
Totaal (excl. BTW) | € 5,05
BTW | € 1,06
Totaal (incl. BTW) | € 6,11

So far, the numbers are correct.

**Mollie test gateway:**
Mollie Test Payment authorize payment for a total amount: €6,11

So far, the numbers are correct.

**Admin orders overview:**
G.T. Base and G.T. Purchased both columns show €6,11

So far, the numbers are correct.

**In the admin, open the order, and  things start to break:**

Subtotal | €3.44
Payment Fee | €1.95
Shipping & Handling | €0.00
Grand Total (Excl.Tax) | €5.05
Tax | €1.06
Grand Total (Incl.Tax) | €6.11
**Total Paid | €6.45**
Total Refunded | €0.00
Total Due | €0.00

Same page, looking at the payment history, we see:

 Jun 15, 2022 12:17:52 PM|Processing
Customer Notification Not Applicable
Bedrag van **€ 6,45** via betaalplatform geregistreerd. Transactie-ID: "ord_r2klsa".

Jun 15, 2022 12:17:52 PM|Processing
Customer Notification Not Applicable
Autorisatiewaarde **€ 6,11**. Transactie-ID: "ord_r2klsa". 

Where does this number (€6,45) come from?
We cannot attribute it to calculating tax twice, or calculating tax on prices including tax.

**Checking the invoice, we see following numbers:**

Subtotal | €3.44
Payment Fee | €1.95
Grand Total (Excl.Tax) | €5.39
Tax | €1.06
Grand Total (Incl.Tax) | €6.45

**Expected behavior (Payment Fee is the total, including tax amount):**
All screens and pages show consistent numbers, the Customer Notifications show same values for transaction value and registered payment values.

**Comment by kasper-agg** [comment] 2022-06-15 11:10
It looks like the Tax component of the Payment Fee is duplicated: 
€1,95 / 1.21 ~= €0,34
€6,45 - €6,11 = €0,34

**Comment by kasper-agg** [comment] 2022-07-19 17:09
Is this thing on?

**Comment by Frank-Magmodules** [comment] 2022-07-19 17:35
HI @kasper-agg ,

Thank you for opening this issue and sorry for my late response on this, we've tried to reproduce the issue that you describe but we can't reproduce this issue. Can you please share the details of this environment through our [support form](https://www.magmodules.eu/support-form.html) so we can take a look with you?

**Comment by kasper-agg** [comment] 2022-07-20 06:50
Hi Frank, no worries. I'll fill in the form, thnx!

**Comment by kasper-agg** [comment] 2022-07-28 11:54
Fix in PR for Release #224 fixes this issue :tada:

**Comment by Frank-Magmodules** [comment] 2022-07-29 14:14
Hi @kasper-agg ,

We are happy to share that we've just released the new [5.7.1](https://github.com/mollie/Magento/releases/tag/v5.7.1) version with a fix for your issue. Thank you for the detailed issue report on this issue and your willingness to share your environment details, we are closing the issue now.

**Closed** 2022-07-29 14:16 UTC

**Comment by kasper-agg** [comment] 2022-07-30 14:02
Any time, many thanks for looking into it, appreciate it!
